version: '3'

services:
  mariadb:
    container_name: db
    build: ./requirements/mariadb
    volumes:      
      - /home/mazhari/data/mariadb:/var/lib/mysql
    env_file: .env
    networks:
      - web
    restart: always
  wordpress:
    depends_on: 
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - /home/mazhari/data/wordpress:/var/www/html
    networks:
      - web
    restart: always
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - /home/mazhari/data/wordpress:/var/www/html
    networks:
      - web
    restart: always

networks:
  web:
    name: web
    driver: bridge