FROM debian:buster

RUN apt-get -y update \
    && apt-get install -y mariadb-server \
    && mysql_install_db

COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/

COPY ./tools/init_script.sh .

RUN chmod +x ./init_script.sh

ENTRYPOINT ["./init_script.sh"]
CMD ["mysqld_safe"]