FROM debian:buster

RUN apt update -y \
&& apt install mariadb-server mariadb-client -y && mysql_install_db

COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./tools/config.sh /home/tools/config.sh

RUN chmod 700 /home/tools/config.sh

ENTRYPOINT ["/home/tools/config.sh"]
CMD ["mysqld"]
