FROM debian:buster

RUN apt update -y\
    && apt install php-fpm php-cli php-mysql -y\
    && apt install wget -y

COPY ./conf /home/conf

RUN bash < /home/conf/installwp.sh

RUN cp /home/conf/www.conf /etc/php/7.3/fpm/pool.d/www.conf

RUN cp /home/conf/wp-config.php /var/www/html/wp-config.php

CMD ["bash"]