CREATE USER 'root'@'%' IDENTIFIED BY '123456789';
CREATE USER 'wpuser'@'%' IDENTIFIED BY '123';

CREATE DATABASE wp;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON wp.* TO 'wpuser'@'%';
FLUSH PRIVILEGES;